# Generated by Django 6.0.5 on 2026-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('yas', models.IntegerField(verbose_name='Yaş')),
                ('sehir', models.CharField(max_length=50, verbose_name='Yaşadığım Şehir')),
                ('meslek', models.CharField(max_length=100, verbose_name='Meslek')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='Github URL')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='profil_fotograflari/', verbose_name='Güncel Fotoğraf')),
            ],
            options={
                'verbose_name': 'Hakkımda Bilgisi',
                'verbose_name_plural': 'Hakkımda Bilgileri',
            },
        ),
    ]
