# Generated by Django 6.0.5 on 2026-06-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hakkimda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mesaj', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hakkimda',
            options={'verbose_name': 'Hakkında Bilgisi', 'verbose_name_plural': 'Hakkında Bilgileri'},
        ),
        migrations.AlterField(
            model_name='hakkimda',
            name='meslek',
            field=models.CharField(max_length=100, verbose_name='Bölüm / Meslek'),
        ),
        migrations.AlterField(
            model_name='hakkimda',
            name='sehir',
            field=models.CharField(max_length=50, verbose_name='Yaşadığın Şehir'),
        ),
    ]
